print("                   \\|||/           ")
print('                   (o o)            ')
print('        |~~~~~~oo0~~(_)~~~~~~~~~~|  ')
print('        |    Please don\'t feed   | ')
print('        |       THE TROLLS       |  ')
print('        \'~~~~~~~~~~~~~~~~~0oo~~~~\'')
print('                  |__|__|           ')
print('                   || ||            ')
print('                  oo0 0oo           ')
